cwlVersion: v1.0
class: Workflow


requirements:
  - class: SubworkflowFeatureRequirement
  - class: StepInputExpressionRequirement
  - class: InlineJavascriptRequirement
  - class: MultipleInputFeatureRequirement


inputs:

  alias:
    type: string
    label: "Experiment short name/Alias"
    sd:preview:
      position: 1

  genome:
    type:
      type: enum
      symbols:
      - "mm10"
      - "hg19"
      - "hg38"
    label: "Genome type"
    doc: "Genome type, such as mm10, hg19, hg38, etc"


outputs:

  genome_data:
    type: Directory
    outputSource: altanalyze_prepare_genome/genome_data
    label: AltAnalyze genome data
    doc: |
      Pre-downloaded Ensembl database for the specific genome

  altanalyze_prepare_genome_stdout_log:
    type: File
    outputSource: altanalyze_prepare_genome/stdout_log
    label: stdout log generated by altanalyze prepare genome
    doc: |
      stdout log generated by altanalyze prepare genome

  altanalyze_prepare_genome_stderr_log:
    type: File
    outputSource: altanalyze_prepare_genome/stderr_log
    label: stderr log generated by altanalyze prepare genome
    doc: |
      stderr log generated by altanalyze prepare genome


steps:

  altanalyze_prepare_genome:
    run: ../tools/altanalyze-prepare-genome.cwl
    in:
      genome: genome
    out:
    - genome_data
    - stdout_log
    - stderr_log


$namespaces:
  s: http://schema.org/

$schemas:
- https://github.com/schemaorg/schemaorg/raw/main/data/releases/11.01/schemaorg-current-http.rdf

s:name: "AltAnalyze Build Reference Indices"
label: "AltAnalyze Build Reference Indices"
s:alternateName: "Builds reference genome indices for AltAnalyze ICGS and AltAnalyze CellHarmony experiments"

s:downloadUrl: https://raw.githubusercontent.com/datirium/workflows/master/workflows/altanalyze-prepare-genome.cwl
s:codeRepository: https://github.com/datirium/workflows
s:license: http://www.apache.org/licenses/LICENSE-2.0

s:isPartOf:
  class: s:CreativeWork
  s:name: Common Workflow Language
  s:url: http://commonwl.org/

s:creator:
- class: s:Organization
  s:legalName: "Cincinnati Children's Hospital Medical Center"
  s:location:
  - class: s:PostalAddress
    s:addressCountry: "USA"
    s:addressLocality: "Cincinnati"
    s:addressRegion: "OH"
    s:postalCode: "45229"
    s:streetAddress: "3333 Burnet Ave"
    s:telephone: "+1(513)636-4200"
  s:logo: "https://www.cincinnatichildrens.org/-/media/cincinnati%20childrens/global%20shared/childrens-logo-new.png"
  s:department:
  - class: s:Organization
    s:legalName: "Allergy and Immunology"
    s:department:
    - class: s:Organization
      s:legalName: "Barski Research Lab"
      s:member:
      - class: s:Person
        s:name: Michael Kotliar
        s:email: mailto:misha.kotliar@gmail.com
        s:sameAs:
        - id: http://orcid.org/0000-0002-6486-3898


doc: |
  AltAnalyze Build Reference Indices
  ==================================