cwlVersion: v1.1
class: Workflow


requirements:
  - class: SubworkflowFeatureRequirement
  - class: StepInputExpressionRequirement
  - class: InlineJavascriptRequirement
  - class: MultipleInputFeatureRequirement


'sd:upstream':
  genome_indices:
    - "https://github.com/datirium/workflows/workflows/genome-indices.cwl"
    - "genome-indices.cwl"


inputs:

  alias:
    type: string
    label: "Experiment short name/alias"
    sd:preview:
      position: 1

  genome_fasta_file:
    type: File
    label: "Genome Type"
    doc: "Reference genome FASTA file that includes all chromosomes"
    'sd:upstreamSource': "genome_indices/fasta_output"
    'sd:localLabel': true

  annotation_gtf_file:
    type: File
    label: "Genome Type"
    doc: "GTF annotation file that includes refGene and mitochondrial DNA annotations"
    'sd:upstreamSource': "genome_indices/annotation_gtf"
    'sd:localLabel': true

  workflow_type:
    type:
    - "null"
    - type: enum
      name: "workflow_type"
      symbols:
      - standard
      - lamanno
      - nucleus
      - kite
    default: "lamanno"
    label: "Workflow type"
    doc: |
      Type of workflow. Use lamanno to calculate RNA velocity based
      on La Manno et al. 2018 logic. Use nucleus to calculate RNA
      velocity on single-nucleus RNA-seq reads.


outputs:

  kallisto_index_file:
    type: File
    outputSource: kb_ref/kallisto_index_file
    label: "kallisto | bustools index file"
    doc: |
      kallisto | bustools index file

  tx_to_gene_mapping_file:
    type: File
    outputSource: kb_ref/tx_to_gene_mapping_file
    label: "Transcript-to-gene mapping TSV file"
    doc: |
      Transcript-to-gene mapping TSV file

  tx_fasta_file:
    type: File
    outputSource: kb_ref/tx_fasta_file
    label: "Transcript FASTA or mismatch FASTA file"
    doc: |
      Transcript FASTA (for lamanno or nucleus workflow_type)
      or mismatch FASTA (for kite workflow_type) file

  intron_fasta_file:
    type: File?
    outputSource: kb_ref/intron_fasta_file
    label: "Intron FASTA file"
    doc: |
      Intron FASTA file

  tx_to_capture_mapping_file:
    type: File?
    outputSource: kb_ref/tx_to_capture_mapping_file
    label: "Transcripts-to-capture mapping TSV file"
    doc: |
      Transcripts-to-capture mapping TSV file

  intron_tx_to_capture_mapping_file:
    type: File?
    outputSource: kb_ref/intron_tx_to_capture_mapping_file
    label: "Intron transcripts-to-capture mapping TSV file"
    doc: |
      Intron transcripts-to-capture mapping TSV file

  kb_ref_stdout_log:
    type: File
    outputSource: kb_ref/stdout_log
    label: "stdout log generated by kallisto | bustools"
    doc: |
      stdout log generated by kallisto | bustools

  kb_ref_stderr_log:
    type: File
    outputSource: kb_ref/stderr_log
    label: "stderr log generated by kallisto | bustools"
    doc: |
      stderr log generated by kallisto | bustools


steps:

  kb_ref:
    run: ../tools/kb-ref.cwl
    in:
      genome_fasta_file: genome_fasta_file
      annotation_gtf_file: annotation_gtf_file
      workflow_type: workflow_type
    out:
    - kallisto_index_file
    - tx_to_gene_mapping_file
    - tx_fasta_file
    - intron_fasta_file
    - tx_to_capture_mapping_file
    - intron_tx_to_capture_mapping_file
    - stdout_log
    - stderr_log


$namespaces:
  s: http://schema.org/

$schemas:
- https://github.com/schemaorg/schemaorg/raw/main/data/releases/11.01/schemaorg-current-http.rdf

s:name: "Kallisto | BUStools Build Reference Indices"
label: "Kallisto | BUStools Build Reference Indices"
s:alternateName: "Builds a kallisto index and transcript-to-gene mapping"

s:downloadUrl: https://raw.githubusercontent.com/Barski-lab/workflows-datirium/master/workflows/kb-ref.cwl
s:codeRepository: https://github.com/Barski-lab/workflows-datirium
s:license: http://www.apache.org/licenses/LICENSE-2.0

s:isPartOf:
  class: s:CreativeWork
  s:name: Common Workflow Language
  s:url: http://commonwl.org/

s:creator:
- class: s:Organization
  s:legalName: "Cincinnati Children's Hospital Medical Center"
  s:location:
  - class: s:PostalAddress
    s:addressCountry: "USA"
    s:addressLocality: "Cincinnati"
    s:addressRegion: "OH"
    s:postalCode: "45229"
    s:streetAddress: "3333 Burnet Ave"
    s:telephone: "+1(513)636-4200"
  s:logo: "https://www.cincinnatichildrens.org/-/media/cincinnati%20childrens/global%20shared/childrens-logo-new.png"
  s:department:
  - class: s:Organization
    s:legalName: "Allergy and Immunology"
    s:department:
    - class: s:Organization
      s:legalName: "Barski Research Lab"
      s:member:
      - class: s:Person
        s:name: Michael Kotliar
        s:email: mailto:misha.kotliar@gmail.com
        s:sameAs:
        - id: http://orcid.org/0000-0002-6486-3898


doc: |
  Kallisto | BUStools Build Reference Indices
  ===========================================

  Builds a kallisto index and transcript-to-gene mapping