cwlVersion: v1.0
class: Workflow
requirements:
- class: SubworkflowFeatureRequirement
- class: StepInputExpressionRequirement
- class: InlineJavascriptRequirement
- class: MultipleInputFeatureRequirement
inputs:
  alias:
    type: string
    label: Analysis name
    sd:preview:
      position: 1
  query_data_rds:
    type:
    - File
    - type: array
      items: File
    label: RDS file(s) produced by BD Rhapsody Sequence Analysis Pipeline
    doc: |
      Path to the RDS file(s) to load Seurat object(s)
      from. These files should be generated by the BD
      Rhapsody Sequence Analysis Pipeline and include
      Sample_Tag metadata column.
  sample_tags_metadata:
    type: File
    label: Sample tags metadata file (first column should be sample_tag)
    doc: |
      Path to the TSV/CSV file to assign names to the
      sample tags. This file must include exactly two
      columns. First column is a 'sample_tag'. It should
      correspond to all unique values from the 'Sample_Tag'
      column of the loaded Seurat object(s). Second column
      may have an arbitrary name. But it should include
      unique names for each sample tag.
  split_by_origin:
    type: boolean?
    default: false
    label: Split each sample tag by origin
    doc: "When assigning names to the sample tags, split \neach of them by origin (the RDS file the data\nwas loaded from). \nDefault: do not split\n"
    sd:layout:
      advanced: true
  export_html_report:
    type: boolean?
    default: true
    label: Show HTML report
    doc: |
      Export tehcnical report in HTML format.
      Default: true
    sd:layout:
      advanced: true
  threads:
    type:
    - 'null'
    - type: enum
      symbols:
      - '1'
      - '2'
      - '3'
      - '4'
      - '5'
      - '6'
    default: '4'
    label: Cores/CPUs
    doc: |
      Parallelization parameter to define the
      number of cores/CPUs that can be utilized
      simultaneously.
      Default: 4
    sd:layout:
      advanced: true
outputs:
  filtered_feature_bc_matrix_folder:
    type: File
    outputSource: sc_rna_load_rhapsody/feature_bc_matrices_folder
    label: TAR-gzipped folder with the feature-barcode matrix in MEX format
    doc: "Compressed folder with the merged feature-barcode \nmatrix from the loaded RDS files produced by the \nBD Rhapsody Sequence Analysis Pipeline. \nMEX format (TAR-gzipped).\n"
  aggregation_metadata:
    type: File?
    outputSource: sc_rna_load_rhapsody/aggregation_metadata
    label: Aggregation metadata in TSV format
    doc: |
      Aggregation metadata file with names assigned
      to sample tags. The row order corresponds to
      the numeric suffixes added to cell barcodes in
      the merged feature-barcode matrix.
      TSV format.
  seurat_data_rds:
    type: File
    outputSource: sc_rna_load_rhapsody/seurat_data_rds
    label: Seurat object in RDS format
    doc: |
      Seurat object.
      RDS format.
  sc_report_html_file:
    type: File?
    outputSource: sc_rna_load_rhapsody/sc_report_html_file
    label: Analysis log
    doc: |
      Tehcnical report.
      HTML format.
    sd:visualPlugins:
    - linkList:
        tab: Overview
        target: _blank
  sc_rna_load_rhapsody_stdout_log:
    type: File
    outputSource: sc_rna_load_rhapsody/stdout_log
    label: Output log
    doc: |
      Stdout log from the sc_rna_load_rhapsody step.
  sc_rna_load_rhapsody_stderr_log:
    type: File
    outputSource: sc_rna_load_rhapsody/stderr_log
    label: Error log
    doc: |
      Stderr log from the sc_rna_load_rhapsody step.
steps:
  sc_rna_load_rhapsody:
    run: ../tools/sc-rna-load-rhapsody.cwl
    in:
      query_data_rds: query_data_rds
      sample_tags_metadata: sample_tags_metadata
      split_by_origin: split_by_origin
      export_html_report: export_html_report
      verbose:
        default: true
      parallel_memory_limit:
        default: 32
      vector_memory_limit:
        default: 128
      threads:
        source: threads
        valueFrom: $(parseInt(self))
    out:
    - feature_bc_matrices_folder
    - aggregation_metadata
    - seurat_data_rds
    - sc_report_html_file
    - stdout_log
    - stderr_log
label: Single-cell RNA-Seq BD Rhapsody Import
doc: |
  Single-cell RNA-Seq BD Rhapsody Import

  Imports RDS files produced by the BD Rhapsody
  Sequence Analysis Pipeline. Assigns names to the
  sample tags based on the provided metadata file.
  Exports results into compressed feature barcode
  matrix and RDS files.
sd:version: 100
