cwlVersion: v1.1
class: Workflow


requirements:
  - class: SubworkflowFeatureRequirement
  - class: StepInputExpressionRequirement
  - class: MultipleInputFeatureRequirement
  - class: InlineJavascriptRequirement
    expressionLib:
    - var split_numbers = function(line) {
          let splitted_line = line?line.split(/[\s,]+/).map(parseFloat):null;
          return (splitted_line && !!splitted_line.length)?splitted_line:null;
      };


"sd:upstream":
  sc_rna_sample:
  - "cellranger-aggr.cwl"
  - "single-cell-preprocess-cellranger.cwl"
  - "cellranger-multi.cwl"
  - "sc-format-transform.cwl"
  - "sc-rna-load-rhapsody.cwl"


inputs:

  alias:
    type: string
    label: "Analysis name"
    sd:preview:
      position: 1

  filtered_feature_bc_matrix_folder:
    type: File
    label: "Cell Ranger RNA or RNA+VDJ Sample"
    doc: |
      Any "Cell Ranger RNA or RNA+VDJ Sample"
      that produces gene expression data in
      a form of compressed feature-barcode
      matrix in a MEX format, optional annotated
      V(D)J contigs data, and optional aggregation
      metadata file in TSV/CSV format. This
      sample can be obtained from one of the
      following pipelines: "Cell Ranger Count
      (RNA)", "Cell Ranger Count (RNA+VDJ)",
      or "Cell Ranger Aggregate (RNA, RNA+VDJ)"
    "sd:upstreamSource": "sc_rna_sample/filtered_feature_bc_matrix_folder"
    "sd:localLabel": true

  aggregation_metadata:
    type: File?
    "sd:upstreamSource": "sc_rna_sample/aggregation_metadata"

  grouping_data:
    type: File?
    label: "Datasets grouping (optional)"
    doc: |
      If the selected "Cell Ranger RNA or
      RNA+VDJ Sample" includes multiple
      aggregated datasets, each dataset
      can be assigned to a separate group
      by providing a TSV/CSV file with
      "library_id" and "condition"
      columns. Obtain this file from
      the "aggregation_metadata.csv"
      output generated by "Cell Ranger
      Aggregate (RNA, RNA+VDJ)" and
      accessible on the "Files" tab. Remove
      all columns except the "library_id".
      Add the group names for each dataset
      in a separate column named "condition".

  barcodes_data:
    type: File?
    label: "Selected cell barcodes (optional)"
    doc: |
      A TSV/CSV file to optionally prefilter
      the single cell data by including only
      the cells with the selected barcodes.
      The provided file should include at
      least one column named "barcode", with
      one cell barcode per line. All other
      columns, except for "barcode", will be
      added to the single cell metadata loaded
      from "Cell Ranger RNA or RNA+VDJ Sample"
      and can be utilized in the current or
      future steps of analysis.

  remove_doublets:
    type: boolean?
    default: false
    label: "Remove doublets"
    doc: |
      Quality control filtering parameter
      to remove cells identified as doublets.
      Default: do not remove
    "sd:layout":
      advanced: true

  minimum_umis:
    type: string?
    default: "500"
    label: "Minimum number of RNA reads per cell"
    doc: |
      Quality control filtering threshold
      to exclude from the analysis all
      cells with the number of RNA reads
      smaller than the provided value.
      If the selected "Cell Ranger RNA or
      RNA+VDJ Sample" includes multiple
      aggregated datasets, each of them
      can be filtered independently by
      providing comma or space-separated
      list of filtering thresholds. The
      order and number of the specified
      values need to match with the datasets
      order from the "aggregation_metadata.csv"
      output generated by "Cell Ranger RNA or
      RNA+VDJ Sample" and accessible on the
      "Files" tab. Any 0 will be replaced
      with the auto-estimated threshold
      (median - 2.5 * MAD) calculated per
      dataset.
      Default: 500
    "sd:layout":
      advanced: true

  minimum_genes:
    type: string?
    default: "250"
    label: "Minimum number of genes per cell"
    doc: |
      Quality control filtering threshold
      to exclude from the analysis all
      cells with the number of expressed
      genes smaller than the provided value.
      If the selected "Cell Ranger RNA or
      RNA+VDJ Sample" includes multiple
      aggregated datasets, each of them
      can be filtered independently by
      providing comma or space-separated
      list of filtering thresholds. The
      order and number of the specified
      values need to match with the datasets
      order from the "aggregation_metadata.csv"
      output generated by "Cell Ranger RNA or
      RNA+VDJ Sample" and accessible on the
      "Files" tab. Any 0 will be replaced with
      the auto-estimated threshold (median -
      - 2.5 * MAD) calculated per dataset.
      Default: 250
    "sd:layout":
      advanced: true

  maximum_genes:
    type: string?
    default: "5000"
    label: "Maximum number of genes per cell"
    doc: |
      Quality control filtering threshold
      to exclude from the analysis all
      cells with the number of expressed
      genes bigger than the provided value.
      If the selected "Cell Ranger RNA or
      RNA+VDJ Sample" includes multiple
      aggregated datasets, each of them
      can be filtered independently by
      providing comma or space-separated
      list of filtering thresholds. The
      order and number of the specified
      values need to match with the datasets
      order from the "aggregation_metadata.csv"
      output generated by "Cell Ranger RNA or
      RNA+VDJ Sample" and accessible on the
      "Files" tab. Any 0 will be replaced with
      the auto-estimated threshold (median +
      + 5 * MAD) calculated per dataset.
      Default: 5000
    "sd:layout":
      advanced: true

  mito_pattern:
    type: string?
    default: "^mt-|^MT-"
    label: "Mitochondrial genes pattern"
    doc: |
      Regex pattern to identify mitochondrial
      genes based on their names.
      Default: "^mt-|^MT-"
    "sd:layout":
      advanced: true

  maximum_mito_perc:
    type: float?
    default: 5
    label: "Maximum mitochondrial percentage per cell"
    doc: |
      Quality control filtering threshold
      to exclude from the analysis all
      cells with the percentage of RNA reads
      mapped to mitochondrial genes exceeding
      the provided value. Set to 0 for using
      an auto-estimated threshold equal to
      the maximum among (median + 2 * MAD)
      values calculated per dataset.
      Default: 5
    "sd:layout":
      advanced: true

  minimum_novelty_score:
    type: string?
    default: "0.8"
    label: "Minimum novelty score per cell"
    doc: |
      Quality control filtering threshold
      to exclude from the analysis all
      cells with the novelty scores
      smaller than the provided value.
      This QC metrics indicates the overall
      transcriptomic dissimilarity of the
      cells and is calculated as the ratio
      of log10(Genes) to log10(RNA UMI).
      If the selected "Cell Ranger RNA or
      RNA+VDJ Sample" includes multiple
      aggregated datasets, each of them
      can be filtered independently by
      providing comma or space-separated
      list of filtering thresholds. The
      order and number of the specified
      values need to match with the datasets
      order from the "aggregation_metadata.csv"
      output generated by "Cell Ranger RNA or
      RNA+VDJ Sample" and accessible on the
      "Files" tab.
      tab. Default: 0.8
    "sd:layout":
      advanced: true

  export_loupe_data:
    type: boolean?
    default: false
    label: "Save raw counts to Loupe file. I confirm that data is generated by 10x technology and accept the EULA available at https://10xgen.com/EULA"
    doc: |
      Save raw counts from the RNA assay to Loupe file. By
      enabling this feature you accept the End-User License
      Agreement available at https://10xgen.com/EULA.
      Default: false
    "sd:layout":
      advanced: true

  export_html_report:
    type: boolean?
    default: true
    label: "Show HTML report"
    doc: |
      Export tehcnical report in HTML format.
      Default: true
    "sd:layout":
      advanced: true

  color_theme:
    type:
    - "null"
    - type: enum
      symbols:
      - "gray"
      - "bw"
      - "linedraw"
      - "light"
      - "dark"
      - "minimal"
      - "classic"
      - "void"
    default: "classic"
    label: "Color theme for all generated plots"
    doc: |
      Color theme for all generated plots. One of gray, bw, linedraw, light,
      dark, minimal, classic, void.
      Default: classic
    "sd:layout":
      advanced: true

  threads:
    type:
    - "null"
    - type: enum
      symbols:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "6"
    default: "4"
    label: "Number of cores/cpus to use"
    doc: |
      Parallelization parameter to define the
      number of cores/CPUs that can be utilized
      simultaneously.
      Default: 4
    "sd:layout":
      advanced: true


outputs:

  raw_1_2_qc_mtrcs_pca_plot_png:
    type: File?
    outputSource: sc_rna_filter/raw_1_2_qc_mtrcs_pca_plot_png
    label: "QC metrics PCA (unfiltered, PC1/PC2)"
    doc: |
      QC metrics PCA.
      Unfiltered; PC1/PC2.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Unfiltered"
        Caption: "QC metrics PCA (unfiltered, PC1/PC2)"

  raw_2_3_qc_mtrcs_pca_plot_png:
    type: File?
    outputSource: sc_rna_filter/raw_2_3_qc_mtrcs_pca_plot_png
    label: "QC metrics PCA (unfiltered, PC2/PC3)"
    doc: |
      QC metrics PCA.
      Unfiltered; PC2/PC3.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Unfiltered"
        Caption: "QC metrics PCA (unfiltered, PC2/PC3)"

  raw_cell_cnts_plot_png:
    type: File?
    outputSource: sc_rna_filter/raw_cell_cnts_plot_png
    label: "Number of cells per dataset (unfiltered)"
    doc: |
      Number of cells per dataset.
      Unfiltered.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Unfiltered"
        Caption: "Number of cells per dataset (unfiltered)"

  raw_umi_dnst_plot_png:
    type: File?
    outputSource: sc_rna_filter/raw_umi_dnst_plot_png
    label: "Distribution of RNA reads per cell (unfiltered)"
    doc: |
      Distribution of RNA reads per cell.
      Unfiltered.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Unfiltered"
        Caption: "Distribution of RNA reads per cell (unfiltered)"

  raw_gene_dnst_plot_png:
    type: File?
    outputSource: sc_rna_filter/raw_gene_dnst_plot_png
    label: "Distribution of genes per cell (unfiltered)"
    doc: |
      Distribution of genes per cell.
      Unfiltered.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Unfiltered"
        Caption: "Distribution of genes per cell (unfiltered)"

  raw_gene_umi_plot_png:
    type: File?
    outputSource: sc_rna_filter/raw_gene_umi_plot_png
    label: "Genes vs RNA reads per cell (unfiltered)"
    doc: |
      Genes vs RNA reads per cell.
      Unfiltered.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Unfiltered"
        Caption: "Genes vs RNA reads per cell (unfiltered)"

  raw_umi_mito_plot_png:
    type: File?
    outputSource: sc_rna_filter/raw_umi_mito_plot_png
    label: "RNA reads vs mitochondrial percentage per cell (unfiltered)"
    doc: |
      RNA reads vs mitochondrial percentage
      per cell.
      Unfiltered.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Unfiltered"
        Caption: "RNA reads vs mitochondrial percentage per cell (unfiltered)"

  raw_mito_dnst_plot_png:
    type: File?
    outputSource: sc_rna_filter/raw_mito_dnst_plot_png
    label: "Distribution of RNA reads mapped to mitochondrial genes per cell (unfiltered)"
    doc: |
      Distribution of RNA reads mapped
      to mitochondrial genes per cell.
      Unfiltered.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Unfiltered"
        Caption: "Distribution of RNA reads mapped to mitochondrial genes per cell (unfiltered)"

  raw_nvlt_dnst_plot_png:
    type: File?
    outputSource: sc_rna_filter/raw_nvlt_dnst_plot_png
    label: "Distribution of novelty score per cell (unfiltered)"
    doc: |
      Distribution of novelty score per cell.
      Unfiltered.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Unfiltered"
        Caption: "Distribution of novelty score per cell (unfiltered)"

  raw_qc_mtrcs_dnst_plot_png:
    type: File?
    outputSource: sc_rna_filter/raw_qc_mtrcs_dnst_plot_png
    label: "Distribution of QC metrics per cell (unfiltered)"
    doc: |
      Distribution of QC metrics per cell.
      Unfiltered.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Unfiltered"
        Caption: "Distribution of QC metrics per cell (unfiltered)"

  raw_rnadbl_plot_png:
    type: File?
    outputSource: sc_rna_filter/raw_rnadbl_plot_png
    label: "Percentage of RNA doublets (unfiltered)"
    doc: |
      Percentage of RNA doublets.
      Unfiltered.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Unfiltered"
        Caption: "Percentage of RNA doublets (unfiltered)"

  raw_umi_dnst_spl_cnd_plot_png:
    type: File?
    outputSource: sc_rna_filter/raw_umi_dnst_spl_cnd_plot_png
    label: "Distribution of RNA reads per cell (unfiltered, split by grouping condition)"
    doc: |
      Distribution of RNA reads per cell.
      Unfiltered; split by grouping condition.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Unfiltered, split by group"
        Caption: "Distribution of RNA reads per cell (unfiltered, split by grouping condition)"

  raw_gene_dnst_spl_cnd_plot_png:
    type: File?
    outputSource: sc_rna_filter/raw_gene_dnst_spl_cnd_plot_png
    label: "Distribution of genes per cell (unfiltered, split by grouping condition)"
    doc: |
      Distribution of genes per cell.
      Unfiltered; split by grouping condition.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Unfiltered, split by group"
        Caption: "Distribution of genes per cell (unfiltered, split by grouping condition)"

  raw_mito_dnst_spl_cnd_plot_png:
    type: File?
    outputSource: sc_rna_filter/raw_mito_dnst_spl_cnd_plot_png
    label: "Distribution of RNA reads mapped to mitochondrial genes per cell (unfiltered, split by grouping condition)"
    doc: |
      Distribution of RNA reads mapped
      to mitochondrial genes per cell.
      Unfiltered; split by grouping condition.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Unfiltered, split by group"
        Caption: "Distribution of RNA reads mapped to mitochondrial genes per cell (unfiltered, split by grouping condition)"

  raw_nvlt_dnst_spl_cnd_plot_png:
    type: File?
    outputSource: sc_rna_filter/raw_nvlt_dnst_spl_cnd_plot_png
    label: "Distribution of novelty score per cell (unfiltered, split by grouping condition)"
    doc: |
      Distribution of novelty score per cell.
      Unfiltered; split by grouping condition.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Unfiltered, split by group"
        Caption: "Distribution of novelty score per cell (unfiltered, split by grouping condition)"

  fltr_1_2_qc_mtrcs_pca_plot_png:
    type: File?
    outputSource: sc_rna_filter/fltr_1_2_qc_mtrcs_pca_plot_png
    label: "QC metrics PCA (filtered, PC1/PC2)"
    doc: |
      QC metrics PCA.
      Filtered; PC1/PC2.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Filtered"
        Caption: "QC metrics PCA (filtered, PC1/PC2)"

  fltr_2_3_qc_mtrcs_pca_plot_png:
    type: File?
    outputSource: sc_rna_filter/fltr_2_3_qc_mtrcs_pca_plot_png
    label: "QC metrics PCA (filtered, PC2/PC3)"
    doc: |
      QC metrics PCA.
      Filtered; PC2/PC3.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Filtered"
        Caption: "QC metrics PCA (filtered, PC2/PC3)"

  fltr_cell_cnts_plot_png:
    type: File?
    outputSource: sc_rna_filter/fltr_cell_cnts_plot_png
    label: "Number of cells per dataset (filtered)"
    doc: |
      Number of cells per dataset.
      Filtered.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Filtered"
        Caption: "Number of cells per dataset (filtered)"

  fltr_umi_dnst_plot_png:
    type: File?
    outputSource: sc_rna_filter/fltr_umi_dnst_plot_png
    label: "Distribution of RNA reads per cell (filtered)"
    doc: |
      Distribution of RNA reads per cell.
      Filtered.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Filtered"
        Caption: "Distribution of RNA reads per cell (filtered)"

  fltr_gene_dnst_plot_png:
    type: File?
    outputSource: sc_rna_filter/fltr_gene_dnst_plot_png
    label: "Distribution of genes per cell (filtered)"
    doc: |
      Distribution of genes per cell.
      Filtered.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Filtered"
        Caption: "Distribution of genes per cell (filtered)"

  fltr_gene_umi_plot_png:
    type: File?
    outputSource: sc_rna_filter/fltr_gene_umi_plot_png
    label: "Genes vs RNA reads per cell (filtered)"
    doc: |
      Genes vs RNA reads per cell.
      Filtered.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Filtered"
        Caption: "Genes vs RNA reads per cell (filtered)"

  fltr_umi_mito_plot_png:
    type: File?
    outputSource: sc_rna_filter/fltr_umi_mito_plot_png
    label: "RNA reads vs mitochondrial percentage per cell (filtered)"
    doc: |
      RNA reads vs mitochondrial percentage
      per cell.
      Filtered.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Filtered"
        Caption: "RNA reads vs mitochondrial percentage per cell (filtered)"

  fltr_mito_dnst_plot_png:
    type: File?
    outputSource: sc_rna_filter/fltr_mito_dnst_plot_png
    label: "Distribution of RNA reads mapped to mitochondrial genes per cell (filtered)"
    doc: |
      Distribution of RNA reads mapped
      to mitochondrial genes per cell.
      Filtered.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Filtered"
        Caption: "Distribution of RNA reads mapped to mitochondrial genes per cell (filtered)"

  fltr_nvlt_dnst_plot_png:
    type: File?
    outputSource: sc_rna_filter/fltr_nvlt_dnst_plot_png
    label: "Distribution of novelty score per cell (filtered)"
    doc: |
      Distribution of novelty score per cell.
      Filtered.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Filtered"
        Caption: "Distribution of novelty score per cell (filtered)"

  fltr_qc_mtrcs_dnst_plot_png:
    type: File?
    outputSource: sc_rna_filter/fltr_qc_mtrcs_dnst_plot_png
    label: "Distribution of QC metrics per cell (filtered)"
    doc: |
      Distribution of QC metrics per cell.
      Filtered.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Filtered"
        Caption: "Distribution of QC metrics per cell (filtered)"

  fltr_rnadbl_plot_png:
    type: File?
    outputSource: sc_rna_filter/fltr_rnadbl_plot_png
    label: "Percentage of RNA doublets (filtered)"
    doc: |
      Percentage of RNA doublets.
      Filtered.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Filtered"
        Caption: "Percentage of RNA doublets (filtered)"

  fltr_umi_dnst_spl_cnd_plot_png:
    type: File?
    outputSource: sc_rna_filter/fltr_umi_dnst_spl_cnd_plot_png
    label: "Distribution of RNA reads per cell (filtered, split by grouping condition)"
    doc: |
      Distribution of RNA reads per cell.
      Filtered; split by grouping condition.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Filtered, split by group"
        Caption: "Distribution of RNA reads per cell (filtered, split by grouping condition)"

  fltr_gene_dnst_spl_cnd_plot_png:
    type: File?
    outputSource: sc_rna_filter/fltr_gene_dnst_spl_cnd_plot_png
    label: "Distribution of genes per cell (filtered, split by grouping condition)"
    doc: |
      Distribution of genes per cell.
      Filtered; split by grouping condition.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Filtered, split by group"
        Caption: "Distribution of genes per cell (filtered, split by grouping condition)"

  fltr_mito_dnst_spl_cnd_plot_png:
    type: File?
    outputSource: sc_rna_filter/fltr_mito_dnst_spl_cnd_plot_png
    label: "Distribution of RNA reads mapped to mitochondrial genes per cell (filtered, split by grouping condition)"
    doc: |
      Distribution of RNA reads mapped
      to mitochondrial genes per cell.
      Filtered; split by grouping condition.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Filtered, split by group"
        Caption: "Distribution of RNA reads mapped to mitochondrial genes per cell (filtered, split by grouping condition)"

  fltr_nvlt_dnst_spl_cnd_plot_png:
    type: File?
    outputSource: sc_rna_filter/fltr_nvlt_dnst_spl_cnd_plot_png
    label: "Distribution of novelty score per cell (filtered, split by grouping condition)"
    doc: |
      Distribution of novelty score per cell.
      Filtered; split by grouping condition.
      PNG format.
    "sd:visualPlugins":
    - image:
        tab: "Filtered, split by group"
        Caption: "Distribution of novelty score per cell (filtered, split by grouping condition)"

  ucsc_cb_html_data:
    type: Directory
    outputSource: sc_rna_filter/ucsc_cb_html_data
    label: "UCSC Cell Browser (data)"
    doc: |
      UCSC Cell Browser html data.

  ucsc_cb_html_file:
    type: File
    outputSource: sc_rna_filter/ucsc_cb_html_file
    label: "UCSC Cell Browser"
    doc: |
      UCSC Cell Browser html index.
    "sd:visualPlugins":
    - linkList:
        tab: "Overview"
        target: "_blank"

  seurat_data_rds:
    type: File
    outputSource: sc_rna_filter/seurat_data_rds
    label: "Seurat object in RDS format"
    doc: |
      Seurat object.
      RDS format.

  datasets_metadata:
    type: File
    outputSource: sc_rna_filter/datasets_metadata
    label: "Example of datasets metadata"
    doc: |
      Example of datasets metadata file
      in TSV format

  seurat_data_cloupe:
    type: File?
    outputSource: sc_rna_filter/seurat_data_cloupe
    label: "Seurat object in Loupe format"
    doc: |
      Seurat object.
      Loupe format.

  pdf_plots:
    type: File
    outputSource: compress_pdf_plots/compressed_folder
    label: "Compressed folder with all PDF plots"
    doc: |
      Compressed folder with all PDF plots.

  sc_report_html_file:
    type: File?
    outputSource: sc_rna_filter/sc_report_html_file
    label: "Analysis log"
    doc: |
      Tehcnical report.
      HTML format.
    "sd:visualPlugins":
    - linkList:
        tab: "Overview"
        target: "_blank"

  sc_rna_filter_stdout_log:
    type: File
    outputSource: sc_rna_filter/stdout_log
    label: "Output log"
    doc: |
      Stdout log from the sc_rna_filter step.

  sc_rna_filter_stderr_log:
    type: File
    outputSource: sc_rna_filter/stderr_log
    label: "Error log"
    doc: |
      Stderr log from the sc_rna_filter step.


steps:

  uncompress_feature_bc_matrices:
    doc: |
      Extracts the content of TAR file into a folder
    run: ../tools/tar-extract.cwl
    in:
      file_to_extract: filtered_feature_bc_matrix_folder
    out:
    - extracted_folder

  sc_rna_filter:
    doc: |
      Filters single-cell RNA-Seq datasets based on the common QC metrics
    run: ../tools/sc-rna-filter.cwl
    in:
      feature_bc_matrices_folder: uncompress_feature_bc_matrices/extracted_folder
      aggregation_metadata: aggregation_metadata
      grouping_data: grouping_data
      barcodes_data: barcodes_data
      rna_minimum_cells:
        default: 1
      minimum_genes:
        source: minimum_genes
        valueFrom: $(split_numbers(self))
      maximum_genes: 
        source: maximum_genes
        valueFrom: $(split_numbers(self))
      minimum_umis:
        source: minimum_umis
        valueFrom: $(split_numbers(self))
      minimum_novelty_score:
        source: minimum_novelty_score
        valueFrom: $(split_numbers(self))
      mito_pattern: mito_pattern
      maximum_mito_perc: maximum_mito_perc
      remove_doublets: remove_doublets
      verbose:
        default: true
      export_ucsc_cb:
        default: true
      export_loupe_data: export_loupe_data
      export_pdf_plots:
        default: true
      color_theme: color_theme
      parallel_memory_limit:
        default: 32
      vector_memory_limit:
        default: 128
      export_html_report: export_html_report
      threads:
        source: threads
        valueFrom: $(parseInt(self))
    out:
    - raw_1_2_qc_mtrcs_pca_plot_png
    - raw_2_3_qc_mtrcs_pca_plot_png
    - raw_cell_cnts_plot_png
    - raw_umi_dnst_plot_png
    - raw_gene_dnst_plot_png
    - raw_gene_umi_plot_png
    - raw_umi_mito_plot_png
    - raw_mito_dnst_plot_png
    - raw_nvlt_dnst_plot_png
    - raw_qc_mtrcs_dnst_plot_png
    - raw_rnadbl_plot_png
    - raw_umi_dnst_spl_cnd_plot_png
    - raw_gene_dnst_spl_cnd_plot_png
    - raw_mito_dnst_spl_cnd_plot_png
    - raw_nvlt_dnst_spl_cnd_plot_png
    - fltr_1_2_qc_mtrcs_pca_plot_png
    - fltr_2_3_qc_mtrcs_pca_plot_png
    - fltr_cell_cnts_plot_png
    - fltr_umi_dnst_plot_png
    - fltr_gene_dnst_plot_png
    - fltr_gene_umi_plot_png
    - fltr_umi_mito_plot_png
    - fltr_mito_dnst_plot_png
    - fltr_nvlt_dnst_plot_png
    - fltr_qc_mtrcs_dnst_plot_png
    - fltr_rnadbl_plot_png
    - fltr_umi_dnst_spl_cnd_plot_png
    - fltr_gene_dnst_spl_cnd_plot_png
    - fltr_mito_dnst_spl_cnd_plot_png
    - fltr_nvlt_dnst_spl_cnd_plot_png
    - all_plots_pdf
    - ucsc_cb_html_data
    - ucsc_cb_html_file
    - seurat_data_rds
    - seurat_data_cloupe
    - datasets_metadata
    - sc_report_html_file
    - stdout_log
    - stderr_log

  folder_pdf_plots:
    run: ../tools/files-to-folder.cwl
    in:
      input_files:
        source:
        - sc_rna_filter/all_plots_pdf
        valueFrom: $(self.flat().filter(n => n))
      folder_basename:
        default: "pdf_plots"
    out:
    - folder

  compress_pdf_plots:
    run: ../tools/tar-compress.cwl
    in:
      folder_to_compress: folder_pdf_plots/folder
    out:
    - compressed_folder


$namespaces:
  s: http://schema.org/

$schemas:
- https://github.com/schemaorg/schemaorg/raw/main/data/releases/11.01/schemaorg-current-http.rdf

label: "Single-Cell RNA-Seq Filtering Analysis"
s:name: "Single-Cell RNA-Seq Filtering Analysis"
s:alternateName: "Single-Cell RNA-Seq Filtering Analysis"

s:downloadUrl: https://raw.githubusercontent.com/Barski-lab/workflows-datirium/master/workflows/sc-rna-filter.cwl
s:codeRepository: https://github.com/Barski-lab/workflows-datirium
s:license: http://www.apache.org/licenses/LICENSE-2.0

s:isPartOf:
  class: s:CreativeWork
  s:name: Common Workflow Language
  s:url: http://commonwl.org/

s:creator:
- class: s:Organization
  s:legalName: "Cincinnati Children's Hospital Medical Center"
  s:location:
  - class: s:PostalAddress
    s:addressCountry: "USA"
    s:addressLocality: "Cincinnati"
    s:addressRegion: "OH"
    s:postalCode: "45229"
    s:streetAddress: "3333 Burnet Ave"
    s:telephone: "+1(513)636-4200"
  s:logo: "https://www.cincinnatichildrens.org/-/media/cincinnati%20childrens/global%20shared/childrens-logo-new.png"
  s:department:
  - class: s:Organization
    s:legalName: "Allergy and Immunology"
    s:department:
    - class: s:Organization
      s:legalName: "Barski Research Lab"
      s:member:
      - class: s:Person
        s:name: Michael Kotliar
        s:email: mailto:misha.kotliar@gmail.com
        s:sameAs:
        - id: http://orcid.org/0000-0002-6486-3898


doc: |
  Single-Cell RNA-Seq Filtering Analysis

  Removes low-quality cells from the outputs of the “Cell
  Ranger Count (RNA)”, “Cell Ranger Count (RNA+VDJ)”, and
  “Cell Ranger Aggregate (RNA, RNA+VDJ)” pipelines. The
  results of this workflow are used in the “Single-Cell
  RNA-Seq Dimensionality Reduction Analysis” pipeline.