cwlVersion: v1.0
class: Workflow


requirements:
  - class: StepInputExpressionRequirement
  - class: InlineJavascriptRequirement
  - class: MultipleInputFeatureRequirement


# 'sd:metadata':
#   - "../metadata/advanced-header.cwl"


'sd:upstream':
  chipseq_sample:
    - "trim-chipseq-se.cwl"
    - "trim-chipseq-pe.cwl"
    - "https://github.com/datirium/workflows/workflows/trim-chipseq-se.cwl"
    - "https://github.com/datirium/workflows/workflows/trim-chipseq-pe.cwl"
  chipseq_control:
    - "trim-chipseq-se.cwl"
    - "trim-chipseq-pe.cwl"
    - "https://github.com/datirium/workflows/workflows/trim-chipseq-se.cwl"
    - "https://github.com/datirium/workflows/workflows/trim-chipseq-pe.cwl"
  genome_indices:
    - "genome-indices.cwl"


inputs:

  alias:
    type: string
    label: "Experiment short name/alias"
    sd:preview:
      position: 1

  peak_file:
    type: File
    format: "http://edamontology.org/format_3468"
    label: "ChIP-Seq experiment"
    doc: "XLS file generated by MACS2"
    'sd:upstreamSource': "chipseq_sample/macs2_called_peaks"
    'sd:localLabel': true

  alignment_file:
    type: File
    secondaryFiles:
    - .bai
    format: "http://edamontology.org/format_2572"
    label: "ChIP-Seq experiment"
    doc: "Coordinate sorted BAM file and BAI index file"
    'sd:upstreamSource': "chipseq_sample/bambai_pair"
    'sd:localLabel': true

  peak_control_file:
    type: File?
    format: "http://edamontology.org/format_3468"
    label: "Control ChIP-Seq experiment"    
    doc: "XLS file generated by MACS2 used as control"
    'sd:upstreamSource': "chipseq_control/macs2_called_peaks"
    'sd:localLabel': true

  annotation_file:
    type: File
    format: "http://edamontology.org/format_3475"
    label: "Genome annotation"
    doc: "TSV genome annotation file"
    'sd:upstreamSource': "genome_indices/annotation"

  chrom_length_file:
    type: File
    format: "http://edamontology.org/format_2330"
    label: "Chromosome length file"
    doc: "Chromosome length file"
    'sd:upstreamSource': "genome_indices/chrom_length"   

  stitching_distance:
    type: int?
    default: 12500
    label: "Maximum distance between two regions that will be stitched together"
    doc: |
      Maximum distance between two regions that will be stitched together.
      For ROSE default is 12.5kb
    'sd:layout':
      advanced: true

  tss_exclusion_zone_size:
    type: int?
    default: 2500
    label: "Exclude regions contained within +/- this distance from TSS (skip TSS exclusion if 0)"
    doc: |
      Exclude regions contained within +/- this distance from TSS in order to account
      for promoter biases (Default: 0; recommended if used: 2500). If this value is 0,
      will not look for a gene file
    'sd:layout':
      advanced: true

  promoter_distance:
    type: int?
    default: 1000
    label: "Promoter distance, bp"
    doc: |
      Max distance from gene TSS (in both direction) overlapping which the peak will
      be assigned to the promoter region. Default: 1000 bp
    'sd:layout':
      advanced: true

  upstream_distance:
    type: int?
    default: 20000
    label: "Upstream distance, bp"
    doc: |
      Max distance from the promoter (only in upstream direction) overlapping which the
      peak will be assigned to the upstream region. Default: 20,000 bp
    'sd:layout':
      advanced: true


outputs:

  super_enhancers_report_file:
    type: File
    format: "http://edamontology.org/format_3475"
    label: "Super-enhancers report file with the nearest genes assigned"
    doc: "Super-enhancers report file with the nearest genes assigned"
    outputSource: add_island_names/output_file
    'sd:visualPlugins':
    - syncfusiongrid:
        tab: 'Super-enhancers'
        Title: 'Super-enhancers'

  super_enhancers_bigbed_file:
    type: File
    format: "http://edamontology.org/format_3004"
    label: "Super-enhancers"
    doc: "Super-enhancers bigBed file"
    outputSource: bed_to_bigbed/bigbed_file
    'sd:visualPlugins':
    - igvbrowser:
        tab: 'IGV Genome Browser'
        id: 'igvbrowser'
        type: 'annotation'
        name: "Super-enhancers"
        displayMode: "COLLAPSE"
        height: 40

  ranked_super_enhancers_plot_png:
    type: File
    format: "http://edamontology.org/format_3603"
    label: "Ranked super-enhancers plot in PNG format"
    doc: "Ranked super-enhancers plot in PNG format"
    outputSource: run_rose/plot_points_pic
    'sd:visualPlugins':
    - image:
        tab: 'Plots'
        Caption: 'Ranked super-enhancers'

  super_enhancers_table:
    type: File
    format: "http://edamontology.org/format_2330"
    label: "Super-enhancers table TXT file"
    doc: "Super-enhancers table TXT file"
    outputSource: run_rose/super_enhancers_table

  all_enhancers_table:
    type: File
    format: "http://edamontology.org/format_2330"
    label: "All enhancers table TXT file"
    doc: "All enhancers table TXT file"
    outputSource: run_rose/all_enhancers_table

  stitched_enhancer_region_map:
    type: File
    format: "http://edamontology.org/format_2330"
    label: "All densities from calculated in stitched enhancers TXT file"
    doc: "All densities from calculated in stitched enhancers TXT file"
    outputSource: run_rose/stitched_enhancer_region_map

  mapped_gff_directory:
    type: File
    format: "http://edamontology.org/format_3981"
    label: "Compressed mapped GFF folder"
    doc: "Compressed mapped GFF folder"
    outputSource: compress_mapped_gff_directory/compressed_folder


steps:

  make_gff:
    run: ../tools/makegff.cwl
    in:
      islands_file: peak_file
      islands_control_file: peak_control_file
    out:
    - gff_file

  run_rose:
    run: ../tools/rose.cwl
    in:
      binding_sites_file: make_gff/gff_file
      bam_file: alignment_file
      annotation_file: annotation_file
      stitch_distance: stitching_distance
      tss_distance: tss_exclusion_zone_size
    out:
    - plot_points_pic
    - gateway_super_enhancers_bed
    - super_enhancers_table
    - stitched_enhancer_region_map
    - all_enhancers_table
    - mapped_gff_directory

  sort_super_enhancers_bed:
    run: ../tools/linux-sort.cwl
    in:
      unsorted_file: run_rose/gateway_super_enhancers_bed
      key:
        default: ["1,1","2,2n","3,3n"]
    out:
    - sorted_file

  bed_to_bigbed:
    run: ../tools/ucsc-bedtobigbed.cwl
    in:
      input_bed: sort_super_enhancers_bed/sorted_file
      bed_type:
        default: "bed3+3"
      chrom_length_file: chrom_length_file
      output_filename:
        source: sort_super_enhancers_bed/sorted_file
        valueFrom: $(self.basename.split('.').slice(0,-1).join('.') + ".bigBed")
    out:
    - bigbed_file

  bed_to_macs:
    in:
      input_file: sort_super_enhancers_bed/sorted_file
    out:
    - output_file
    run:
      cwlVersion: v1.0
      class: CommandLineTool
      requirements:
      - class: DockerRequirement
        dockerPull: biowardrobe2/scidap:v0.0.3
      inputs:
        input_file:
          type: File
          inputBinding:
            position: 5
          doc: Input file to be converted to MACS2 output format
      outputs:
        output_file:
          type: File
          outputBinding:
            glob: "*"
      baseCommand: [bash, '-c']
      arguments:
      - cat $0 | grep -v "#" | grep -v "track" | awk
        'BEGIN {print "chr\tstart\tend\tlength\tabs_summit\tpileup\t-log10(pvalue)\tfold_enrichment\t-log10(qvalue)\tname"}
        {print $1"\t"$2"\t"$3"\t"$3-$2+1"\t0\t0\t0\t0\t0\t"$4}' > `basename $0`
      doc: Tool converts `input_file` to the format compatible with the input of iaintersect from `assign_genes` step

  assign_genes:
    run: ../tools/iaintersect.cwl
    in:
      input_filename: bed_to_macs/output_file
      annotation_filename: annotation_file
      promoter_bp: promoter_distance
      upstream_bp: upstream_distance
    out:
    - result_file

  add_island_names:
    in:
      input_file: [assign_genes/result_file, sort_super_enhancers_bed/sorted_file]
      param:
        source: sort_super_enhancers_bed/sorted_file
        valueFrom: $(self.basename.split('.').slice(0,-1).join('.') + ".tsv")
    out: [output_file]
    run:
      cwlVersion: v1.0
      class: CommandLineTool
      requirements:
      - class: DockerRequirement
        dockerPull: biowardrobe2/scidap:v0.0.3
      inputs:
        input_file:
          type: File[]
          inputBinding:
            position: 5
          doc: TSV file to add extra columns too
        param:
          type: string
          inputBinding:
            position: 6
          doc: Param to set output filename
      outputs:
        output_file:
          type: File
          outputBinding:
            glob: "*"
      baseCommand: [bash, '-c']
      arguments:
      - echo -e "refseq_id\tgene_id\ttxStart\ttxEnd\tstrand\tchrom\tstart\tend\tlength\tregion\tname\tscore" > `basename $2`;
        cat $0 | grep -v refseq_id | paste - $1 | cut -f 1-9,15,19,20 >> `basename $2`

  compress_mapped_gff_directory:
    run: ../tools/tar-compress.cwl
    in:
      folder_to_compress: run_rose/mapped_gff_directory
    out:
    - compressed_folder


$namespaces:
  s: http://schema.org/

$schemas:
- https://github.com/schemaorg/schemaorg/raw/main/data/releases/11.01/schemaorg-current-http.rdf

s:name: "ROSE: rank ordering of super-enhancers"
label: "ROSE: rank ordering of super-enhancers"
s:alternateName: "ROSE: rank ordering of super-enhancers"

s:downloadUrl: https://raw.githubusercontent.com/datirium/workflows/master/workflows/super-enhancer.cwl
s:codeRepository: https://github.com/datirium/workflows
s:license: http://www.apache.org/licenses/LICENSE-2.0

s:isPartOf:
  class: s:CreativeWork
  s:name: Common Workflow Language
  s:url: http://commonwl.org/

s:creator:
- class: s:Organization
  s:legalName: "Cincinnati Children's Hospital Medical Center"
  s:location:
  - class: s:PostalAddress
    s:addressCountry: "USA"
    s:addressLocality: "Cincinnati"
    s:addressRegion: "OH"
    s:postalCode: "45229"
    s:streetAddress: "3333 Burnet Ave"
    s:telephone: "+1(513)636-4200"
  s:logo: "https://www.cincinnatichildrens.org/-/media/cincinnati%20childrens/global%20shared/childrens-logo-new.png"
  s:department:
  - class: s:Organization
    s:legalName: "Allergy and Immunology"
    s:department:
    - class: s:Organization
      s:legalName: "Barski Research Lab"
      s:member:
      - class: s:Person
        s:name: Michael Kotliar
        s:email: mailto:misha.kotliar@gmail.com
        s:sameAs:
        - id: http://orcid.org/0000-0002-6486-3898


doc: |
  Super-enhancers, consist of clusters of enhancers that are densely occupied by
  the master regulators and Mediator. Super-enhancers differ from typical enhancers
  in size, transcription factor density and content, ability to activate transcription,
  and sensitivity to perturbation. Use to create stitched enhancers, and to separate
  super-enhancers from typical enhancers using sequencing data (.bam) given a file of
  previously identified constituent enhancers (.gff)