cwlVersion: v1.0
class: CommandLineTool
requirements:
- class: InlineJavascriptRequirement
- class: EnvVarRequirement
  envDef:
    R_MAX_VSIZE: $((inputs.vector_memory_limit * 1000000000).toString())
hints:
- class: DockerRequirement
  dockerPull: biowardrobe2/sc-tools:v0.0.41
inputs:
  query_data_rds:
    type:
    - File
    - type: array
      items: File
    inputBinding:
      prefix: --rds
    doc: |
      Path to the RDS file(s) to load Seurat object(s)
      from. These files should be generated by the BD
      Rhapsody Sequence Analysis Pipeline and include
      Sample_Tag metadata column.
  sample_tags_metadata:
    type: File
    inputBinding:
      prefix: --metadata
    doc: |
      Path to the TSV/CSV file to assign names to the
      sample tags. This file must include exactly two
      columns. First column is a 'sample_tag'. It should
      correspond to all unique values from the 'Sample_Tag'
      column of the loaded Seurat object(s). Second column
      may have an arbitrary name. But it should include
      unique names for each sample tag.
  split_by_origin:
    type: boolean?
    inputBinding:
      prefix: --split
    doc: "When assigning names to the sample tags, split \neach of them by origin (the RDS file the data\nwas loaded from). \nDefault: do not split\n"
  verbose:
    type: boolean?
    inputBinding:
      prefix: --verbose
    doc: |
      Print debug information.
      Default: false
  export_h5ad_data:
    type: boolean?
    inputBinding:
      prefix: --h5ad
    doc: |
      Save raw counts from the RNA assay to h5ad file.
      Default: false
  export_html_report:
    type: boolean?
    default: false
    doc: |
      Export tehcnical report. HTML format.
      Note, stdout will be less informative.
      Default: false
  output_prefix:
    type: string?
    inputBinding:
      prefix: --output
    doc: |
      Output prefix.
      Default: ./sc
  parallel_memory_limit:
    type: int?
    inputBinding:
      prefix: --memory
    doc: |
      Maximum memory in GB allowed to be shared between the workers
      when using multiple --cpus.
      Default: 32
  vector_memory_limit:
    type: int?
    default: 128
    doc: |
      Maximum vector memory in GB allowed to be used by R.
      Default: 128
  threads:
    type: int?
    inputBinding:
      prefix: --cpus
    doc: |
      Number of cores/cpus to use.
      Default: 1
  seed:
    type: int?
    inputBinding:
      prefix: --seed
    doc: |
      Seed number for random values.
      Default: 42
outputs:
  feature_bc_matrices_folder:
    type: File
    outputBinding:
      glob: '*_bc_matrix.tar.gz'
    doc: "Compressed folder with the merged feature-barcode \nmatrix from the loaded RDS files produced by the \nBD Rhapsody Sequence Analysis Pipeline. \nMEX format (TAR-gzipped).\n"
  aggregation_metadata:
    type: File
    outputBinding:
      glob: '*_aggr.tsv'
    doc: |
      Aggregation metadata file with names assigned
      to sample tags. The row order corresponds to
      the numeric suffixes added to cell barcodes in
      the merged feature-barcode matrix.
      TSV format.
  seurat_data_rds:
    type: File
    outputBinding:
      glob: '*_data.rds'
    doc: |
      Seurat object.
      RDS format.
  seurat_data_h5ad:
    type: File?
    outputBinding:
      glob: '*_counts.h5ad'
    doc: |
      Seurat object.
      H5AD format.
  sc_report_html_file:
    type: File?
    outputBinding:
      glob: sc_report.html
    doc: |
      Tehcnical report.
      HTML format.
  stdout_log:
    type: stdout
  stderr_log:
    type: stderr
baseCommand:
- Rscript
arguments:
- valueFrom: $(inputs.export_html_report?["/usr/local/bin/sc_report_wrapper.R", "/usr/local/bin/sc_rna_load_rhapsody.R"]:"/usr/local/bin/sc_rna_load_rhapsody.R")
stdout: sc_rna_load_rhapsody_stdout.log
stderr: sc_rna_load_rhapsody_stderr.log
label: Single-cell RNA-Seq BD Rhapsody Import
doc: |
  Single-cell RNA-Seq BD Rhapsody Import

  Imports RDS files produced by the BD Rhapsody
  Sequence Analysis Pipeline. Assigns names to the
  sample tags based on the provided metadata file.
  Exports results into compressed feature barcode
  matrix, RDS and h5ad files.
