cwlVersion: v1.0
class: CommandLineTool


requirements:
- class: InlineJavascriptRequirement
- class: EnvVarRequirement
  envDef:
    R_MAX_VSIZE: $((inputs.vector_memory_limit * 1000000000).toString())


hints:
- class: DockerRequirement
  dockerPull: biowardrobe2/sc-tools:v0.0.41


inputs:

  query_data_rds:
    type:
    - File
    - type: array
      items: File
    inputBinding:
      prefix: "--rds"
    doc: |
      Path to the RDS file(s) to load Seurat object(s)
      from. These files should be generated by the BD
      Rhapsody Sequence Analysis Pipeline and include
      Sample_Tag metadata column.

  sample_tags_metadata:
    type: File
    inputBinding:
      prefix: "--metadata"
    doc: |
      Path to the TSV/CSV file to assign names to the
      sample tags. This file must include exactly two
      columns. First column is a 'sample_tag'. It should
      correspond to all unique values from the 'Sample_Tag'
      column of the loaded Seurat object(s). Second column
      may have an arbitrary name. But it should include
      unique names for each sample tag.

  split_by_origin:
    type: boolean?
    inputBinding:
      prefix: "--split"
    doc: |
      When assigning names to the sample tags, split 
      each of them by origin (the RDS file the data
      was loaded from). 
      Default: do not split

  verbose:
    type: boolean?
    inputBinding:
      prefix: "--verbose"
    doc: |
      Print debug information.
      Default: false

  export_h5ad_data:
    type: boolean?
    inputBinding:
      prefix: "--h5ad"
    doc: |
      Save raw counts from the RNA assay to h5ad file.
      Default: false

  export_html_report:
    type: boolean?
    default: false
    doc: |
      Export tehcnical report. HTML format.
      Note, stdout will be less informative.
      Default: false

  output_prefix:
    type: string?
    inputBinding:
      prefix: "--output"
    doc: |
      Output prefix.
      Default: ./sc

  parallel_memory_limit:
    type: int?
    inputBinding:
      prefix: "--memory"
    doc: |
      Maximum memory in GB allowed to be shared between the workers
      when using multiple --cpus.
      Default: 32

  vector_memory_limit:
    type: int?
    default: 128
    doc: |
      Maximum vector memory in GB allowed to be used by R.
      Default: 128

  threads:
    type: int?
    inputBinding:
      prefix: "--cpus"
    doc: |
      Number of cores/cpus to use.
      Default: 1

  seed:
    type: int?
    inputBinding:
      prefix: "--seed"
    doc: |
      Seed number for random values.
      Default: 42


outputs:

  feature_bc_matrices_folder:
    type: File
    outputBinding:
      glob: "*_bc_matrix.tar.gz"
    doc: |
      Compressed folder with the merged feature-barcode 
      matrix from the loaded RDS files produced by the 
      BD Rhapsody Sequence Analysis Pipeline. 
      MEX format (TAR-gzipped).

  aggregation_metadata:
    type: File
    outputBinding:
      glob: "*_aggr.tsv"
    doc: |
      Aggregation metadata file with names assigned
      to sample tags. The row order corresponds to
      the numeric suffixes added to cell barcodes in
      the merged feature-barcode matrix.
      TSV format.

  seurat_data_rds:
    type: File
    outputBinding:
      glob: "*_data.rds"
    doc: |
      Seurat object.
      RDS format.

  seurat_data_h5ad:
    type: File?
    outputBinding:
      glob: "*_counts.h5ad"
    doc: |
      Seurat object.
      H5AD format.

  sc_report_html_file:
    type: File?
    outputBinding:
      glob: "sc_report.html"
    doc: |
      Tehcnical report.
      HTML format.

  stdout_log:
    type: stdout

  stderr_log:
    type: stderr


baseCommand: ["Rscript"]
arguments:
- valueFrom: $(inputs.export_html_report?["/usr/local/bin/sc_report_wrapper.R", "/usr/local/bin/sc_rna_load_rhapsody.R"]:"/usr/local/bin/sc_rna_load_rhapsody.R")

stdout: sc_rna_load_rhapsody_stdout.log
stderr: sc_rna_load_rhapsody_stderr.log


$namespaces:
  s: http://schema.org/

$schemas:
- https://github.com/schemaorg/schemaorg/raw/main/data/releases/11.01/schemaorg-current-http.rdf


label: "Single-cell RNA-Seq BD Rhapsody Import"
s:name: "Single-cell RNA-Seq BD Rhapsody Import"
s:alternateName: "Single-cell RNA-Seq BD Rhapsody Import"

s:downloadUrl: https://raw.githubusercontent.com/Barski-lab/workflows/master/tools/sc-rna-load-rhapsody.cwl
s:codeRepository: https://github.com/Barski-lab/workflows
s:license: http://www.apache.org/licenses/LICENSE-2.0

s:isPartOf:
  class: s:CreativeWork
  s:name: Common Workflow Language
  s:url: http://commonwl.org/

s:creator:
- class: s:Organization
  s:legalName: "Cincinnati Children's Hospital Medical Center"
  s:location:
  - class: s:PostalAddress
    s:addressCountry: "USA"
    s:addressLocality: "Cincinnati"
    s:addressRegion: "OH"
    s:postalCode: "45229"
    s:streetAddress: "3333 Burnet Ave"
    s:telephone: "+1(513)636-4200"
  s:logo: "https://www.cincinnatichildrens.org/-/media/cincinnati%20childrens/global%20shared/childrens-logo-new.png"
  s:department:
  - class: s:Organization
    s:legalName: "Allergy and Immunology"
    s:department:
    - class: s:Organization
      s:legalName: "Barski Research Lab"
      s:member:
      - class: s:Person
        s:name: Michael Kotliar
        s:email: mailto:misha.kotliar@gmail.com
        s:sameAs:
        - id: http://orcid.org/0000-0002-6486-3898


doc: |
  Single-cell RNA-Seq BD Rhapsody Import

  Imports RDS files produced by the BD Rhapsody
  Sequence Analysis Pipeline. Assigns names to the
  sample tags based on the provided metadata file.
  Exports results into compressed feature barcode
  matrix, RDS and h5ad files.


s:about: |
  usage: /usr/local/bin/sc_rna_load_rhapsody.R [-h] --rds RDS [RDS ...]
                                              --metadata METADATA [--split]
                                              [--verbose] [--h5ad]
                                              [--output OUTPUT] [--cpus CPUS]
                                              [--memory MEMORY] [--seed SEED]

  Single-cell RNA-Seq BD Rhapsody Import

  optional arguments:
    -h, --help           show this help message and exit
    --rds RDS [RDS ...]  Path to the RDS file(s) to load Seurat object(s) from.
                        These files should be generated by the BD Rhapsody
                        Sequence Analysis Pipeline and include Sample_Tag
                        metadata column.
    --metadata METADATA  Path to the TSV/CSV file to assign names to the sample
                        tags. This file must include exactly two columns. First
                        column is a 'sample_tag'. It should correspond to all
                        unique values from the 'Sample_Tag' column of the
                        loaded Seurat object(s). Second column may have an
                        arbitrary name. But it should include unique names for
                        each sample tag.
    --split              When assigning names to the sample tags, split each of
                        them by sample (the RDS file the data was loaded from).
                        Default: do not split
    --verbose            Print debug information. Default: false
    --h5ad               Save raw counts from the RNA assay to h5ad file.
                        Default: false
    --output OUTPUT      Output prefix. Default: ./sc
    --cpus CPUS          Number of cores/cpus to use. Default: 1
    --memory MEMORY      Maximum memory in GB allowed to be shared between the
                        workers when using multiple --cpus. Default: 32
    --seed SEED          Seed number for random values. Default: 42