cwlVersion: v1.0
class: CommandLineTool


requirements:
- class: InlineJavascriptRequirement


hints:
- class: DockerRequirement
  dockerPull: biowardrobe2/upsetr:v0.0.1


inputs:

  cluster_files:
    type: File[]
    inputBinding:
      prefix: "--clusters"
    doc: |
      Cellurar barcodes files clustered by genotype
      with Souporcell

  cluster_names:
    type: string[]
    inputBinding:
      prefix: "--aliases"
    doc: |
      Aliases for files provided in --clusters

  output_prefix:
    type: string?
    inputBinding:
      prefix: "--output"
    doc: |
      Output prefix. Default: ./overlap


outputs:

  upset_plot_png:
    type: File
    outputBinding:
      glob: "*.png"
    doc: "UpSet plot in PNG format"

  stdout_log:
    type: stdout

  stderr_log:
    type: stderr


baseCommand: ["souporcell_cluster_overlap.R"]

stdout: upset_stdout.log
stderr: upset_stderr.log


$namespaces:
  s: http://schema.org/

$schemas:
- https://github.com/schemaorg/schemaorg/raw/main/data/releases/11.01/schemaorg-current-http.rdf


label: "Souporcell Cluster Overlap"
s:name: "Souporcell Cluster Overlap"
s:alternateName: "Build upset plot for clustering results generated by multiple runs of Souporcell"

s:downloadUrl: https://raw.githubusercontent.com/Barski-lab/workflows/master/tools/souporcell-cluster-overlap.cwl
s:codeRepository: https://github.com/Barski-lab/workflows
s:license: http://www.apache.org/licenses/LICENSE-2.0

s:isPartOf:
  class: s:CreativeWork
  s:name: Common Workflow Language
  s:url: http://commonwl.org/

s:creator:
- class: s:Organization
  s:legalName: "Cincinnati Children's Hospital Medical Center"
  s:location:
  - class: s:PostalAddress
    s:addressCountry: "USA"
    s:addressLocality: "Cincinnati"
    s:addressRegion: "OH"
    s:postalCode: "45229"
    s:streetAddress: "3333 Burnet Ave"
    s:telephone: "+1(513)636-4200"
  s:logo: "https://www.cincinnatichildrens.org/-/media/cincinnati%20childrens/global%20shared/childrens-logo-new.png"
  s:department:
  - class: s:Organization
    s:legalName: "Allergy and Immunology"
    s:department:
    - class: s:Organization
      s:legalName: "Barski Research Lab"
      s:member:
      - class: s:Person
        s:name: Michael Kotliar
        s:email: mailto:misha.kotliar@gmail.com
        s:sameAs:
        - id: http://orcid.org/0000-0002-6486-3898


doc: |
  Souporcell Cluster Overlap

  Build upset plot for clustering results generated by multiple runs of Souporcell


s:about: |
  usage: souporcell_cluster_overlap.R [-h] --clusters CLUSTERS
                                                    [CLUSTERS ...] --aliases
                                                    ALIASES [ALIASES ...]
                                                    [--output OUTPUT]

  Souporcell Cluster Overlap

  options:
    -h, --help            show this help message and exit
    --clusters CLUSTERS [CLUSTERS ...]
                          Path to the Souporcell generated cluster files
    --aliases ALIASES [ALIASES ...]
                          Aliases for cluster files. Order and number of the
                          provided values should correspond to --clusters.
    --output OUTPUT       Output prefix. Default: ./overlap
